fork: false
real_host: https://harbour.github.io
repo_slug: harbour/core
site_slug: harbour/harbour.github.io
site_branch_and_root: master/
dl_url: https://sourceforge.net/projects/harbour-project/files/
badge_version: "3.0"
license_file: COPYING.txt

example_categories:
  - basic
  - arrays
  - database
  - extensions
  - web
collections:
  example:
    output: true
defaults:
  - scope:
      path: ""
      type: example
    values:
      layout: example

incremental: true
exclude: ["node_modules"]
sass:
  style: compressed
